//go:build conformance

package conformance

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"strings"
	"testing"

	"github.com/kenneth/s3-encryption-gateway/test/harness"
	"github.com/kenneth/s3-encryption-gateway/test/provider"
)

// testPresignedGet verifies that a pre-signed GET URL generated by the gateway
// returns the decrypted plaintext.
func testPresignedGet(t *testing.T, inst provider.Instance) {
	t.Helper()
	gw := harness.StartGateway(t, inst)

	data := []byte("presigned-get-data")
	key := uniqueKey(t)
	put(t, gw, inst.Bucket, key, data)

	// Request a presigned URL from the gateway.
	presignURL := fmt.Sprintf("%s/%s/%s?presign=true&expires=3600",
		gw.URL, inst.Bucket, key)
	resp, err := gw.HTTPClient().Get(presignURL)
	if err != nil {
		t.Fatalf("presign GET request: %v", err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)

	// If the gateway returns a redirect (307) to the presigned URL, follow it.
	if resp.StatusCode == http.StatusTemporaryRedirect || resp.StatusCode == http.StatusFound {
		location := resp.Header.Get("Location")
		if location == "" {
			t.Fatal("presign redirect but no Location header")
		}
		resp2, err := gw.HTTPClient().Get(location)
		if err != nil {
			t.Fatalf("follow presign redirect: %v", err)
		}
		defer resp2.Body.Close()
		body, _ = io.ReadAll(resp2.Body)
		if resp2.StatusCode != http.StatusOK {
			t.Fatalf("presigned GET: status %d: %s", resp2.StatusCode, string(body))
		}
		if !bytes.Equal(body, data) {
			t.Errorf("presigned GET data mismatch")
		}
		return
	}

	// Some gateway implementations generate and return the presigned URL as a
	// header or body rather than a redirect.
	if resp.StatusCode == http.StatusOK {
		// Body may be the presigned URL itself.
		presignedURL := strings.TrimSpace(string(body))
		if strings.HasPrefix(presignedURL, "http") {
			resp3, err := http.Get(presignedURL)
			if err != nil {
				t.Fatalf("presigned URL GET: %v", err)
			}
			defer resp3.Body.Close()
			body3, _ := io.ReadAll(resp3.Body)
			if resp3.StatusCode != http.StatusOK {
				t.Skipf("presigned GET via URL: status %d (backend may not support presigned URLs for encrypted objects)", resp3.StatusCode)
			}
			if !bytes.Equal(body3, data) {
				t.Errorf("presigned GET data mismatch via URL")
			}
			return
		}
		// Response IS the object.
		if !bytes.Equal(body, data) {
			t.Errorf("presigned GET data mismatch (direct response)")
		}
		return
	}

	// Gateway does not implement presigned GET — skip gracefully.
	t.Skipf("presigned GET not implemented or returned unexpected status %d", resp.StatusCode)
}

// testPresignedPut verifies that a pre-signed PUT URL generated by the gateway
// is usable. This test is advisory — many gateway implementations do not
// support presigned PUT for encrypted objects and will return 501; the test
// skips in that case.
func testPresignedPut(t *testing.T, inst provider.Instance) {
	t.Helper()
	gw := harness.StartGateway(t, inst)
	key := uniqueKey(t)

	presignURL := fmt.Sprintf("%s/%s/%s?presign=true&expires=3600&method=PUT",
		gw.URL, inst.Bucket, key)
	resp, err := gw.HTTPClient().Get(presignURL)
	if err != nil {
		t.Fatalf("presign PUT request: %v", err)
	}
	defer resp.Body.Close()
	io.Copy(io.Discard, resp.Body)

	if resp.StatusCode == http.StatusNotImplemented || resp.StatusCode == http.StatusMethodNotAllowed {
		t.Skip("presigned PUT not implemented for encrypted objects (expected)")
	}
	// Otherwise, a presigned URL was returned; consider the test advisory-passed.
}
